version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: drizzle_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: drizzle_user
      POSTGRES_PASSWORD: drizzle_pass
      POSTGRES_DB: drizzle_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
